apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name}}-deployment
  namespace: {{ .Values.namespace.name}}
  labels:
    app: {{ .Values.app.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name}}
      annotations:
        sidecar.istio.io/inject: "true"

      # Enable Vault Agent Injector
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "reef-forge-fe-role"  # Vault role for the app
        vault.hashicorp.com/agent-inject-secret-env: "kv/stripe/dev/secrets" # Vault secret path
        vault.hashicorp.com/agent-inject-template-env: |
          {{`{{- with secret "kv/stripe/dev/secrets" -}}`}}
          {{`NEXT_PUBLIC_STRIPE_PUBLIC_KEY="{{ .Data.data.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}"`}}
          {{`STRIPE_SECRET_KEY="{{ .Data.data.STRIPE_SECRET_KEY }}"`}}
          {{`{{- end }}`}}
        vault.hashicorp.com/secret-volume-path: "/"

    spec:
      serviceAccountName:  {{ .Values.app.name}}-sa # Use the service account

      containers:

      - name: {{ .Values.app.name}}
        image: {{ .Values.app.image.name}}:{{.Values.app.image.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

