import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar/NavBar'
import BasketProvider from './components/BasketContext/BasketContext';
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Reef Forge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >

      <body className={`${inter.className} flex align-middle items-center justify-center bg-slate-100`}>

        <div className='flex w-full flex-col  items-center'>
            <h2 className='flex w-full justify-center pb-1 md:pb-2 pt-1 bg-orange-300'>Free Delivery on order over £50</h2>

          <header>
 

          </header>
          <BasketProvider>
            <div>
            <NavBar />
            </div>

            
            <div className=' bg-slate-200 shadow-2xl h-px'></div>
            <div className=' flex flex-col bg-slate-100  max-w-screen-2xl '>
              {children}


            </div>
          </BasketProvider>

          <div className='flex w-full  items-center'>

          <Footer />

          </div>
        </div>
      </body>
    </html>


  )
}
