app:
  name: reef-forge-frontend
  image:
    name: docker.io/sujan7410/reef-forge-frontend
    tag: release_v1.0.0
namespace:
  name: reef-forge-frontend

vault:
  enabled: true

ports:
  targetPort: 3000
  servicePort: 3000
