apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: reef-forge-cloudflare-cert
  namespace: istio-system
spec:
  secretName: reef-forge-acme-issuer
  issuerRef:
    name: sujantechden-acme-issuer
    kind: ClusterIssuer
  dnsNames:
      - reef-forge.uk
      
