apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: reef-forge-acme-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gcp2.sujangurung@gmail.com

    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: gcp2.sujangurung@gmail.com

          apiKeySecretRef:
            name: sujantechden-cloudflare-api-key-secret
            key: api-key